ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
jwt:
    secret : "secret"
    issuer : "http://127.0.0.0:8888/"
    audience : "http://127.0.0.0:8888/auth/users/me"
    realm : "Access to 'users' protected"

db:
  mongo:
    user: ""
    password: ""